apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: votesahayak
  annotations:
    run.googleapis.com/client-name: gcloud
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/PROJECT_ID/votesahayak
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
          env:
            - name: NODE_ENV
              value: production
            - name: FIREBASE_WEB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-web-api-key
                  key: latest
            - name: FIREBASE_PROJECT_ID
              value: YOUR_PROJECT_ID
            - name: GOOGLE_CLOUD_STORAGE_BUCKET
              value: YOUR_PROJECT_ID-certificates
          ports:
            - containerPort: 8080
